Add modal carousel
barbagrigia/yard-frontend pull request #14
Opened 2017-07-21 20:57 UTC by barbagrigia

2017-07-21 21:30 UTC, evgenyrodionov commented
Ох, убери эффект зума при наведении, некрасиво смотрится

2017-07-21 21:30 UTC, evgenyrodionov commented
Не понял что за бордер внутри

![image](https://user-images.githubusercontent.com/775692/28483239-ee9375be-6e74-11e7-89d1-2215d527f36c.png)

2017-07-21 21:30 UTC, evgenyrodionov commented
Нет анимации переключения

2017-07-21 21:30 UTC, evgenyrodionov commented
Если хочешь что-то сделать лучше по дизайну — всегда лучше сначала обсуди с дизайнером

2017-07-21 22:45 UTC, barbagrigia commented
https://yard-frontend-qhncdppioj.now.sh

2017-07-21 23:02 UTC, barbagrigia commented
https://yard-frontend-idybsaoyiw.now.sh

2017-07-22 00:25 UTC, barbagrigia commented
https://yard-frontend-ubpcxuisve.now.sh

2017-07-22 09:53 UTC, imevro requested changes
Мне понравилось в целом. Пиздато реально.

2017-07-22 09:53 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +      return `translateX(calc(${-active * 100}% + 50vw - 50%))`;
а вынеси эти вычисления в отдельную константу, а то не оч понятно что тут происходит

2017-07-22 09:53 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +  getTransform = (i: number) => {
вынеси из класса, сделай обычной функцией

2017-07-22 16:18 UTC, barbagrigia commented
https://yard-frontend-dosltvhhau.now.sh

2017-07-22 18:18 UTC, imevro requested changes
Красиво в целом

2017-07-22 18:18 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +                scaleRatio="1.2"
поч строкой?

2017-07-22 18:18 UTC, evgenyrodionov commented on src/Complexes/Show/Carousel.jsx
> +  @media (max-width: 1024px) {
давай через mobile first все же

2017-07-22 21:02 UTC, barbagrigia commented
https://yard-frontend-jahdfphnee.now.sh

2017-07-24 12:28 UTC, imevro approved these changes

2017-07-24 12:28 UTC, merged