Adaptive complex page
barbagrigia/yard-frontend pull request #16
Opened 2017-07-29 19:59 UTC by barbagrigia

https://yard-frontend-puqvpblwqm.now.sh

2017-07-30 11:12 UTC, evgenyrodionov commented
Не оч понятно что хар-ки скроллятся

![image](https://user-images.githubusercontent.com/775692/28752813-c7741368-7530-11e7-9d1a-ade68ae71fd1.png)

2017-07-30 11:14 UTC, imevro requested changes

2017-07-30 11:14 UTC, evgenyrodionov commented on src/theme.js
>    blackTwo: '#000',
либо вопрос к дизайнеру, либо blackSecondary

2017-07-30 11:14 UTC, evgenyrodionov commented on src/theme.js
> +  anotherGrey: '#e0e0e1',
опять же

2017-08-01 20:18 UTC, barbagrigia commented
https://yard-frontend-mqiyetywgz.now.sh

2017-08-02 20:12 UTC, imevro approved these changes

2017-08-02 20:12 UTC, merged